name: Build

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

concurrency: # Run release builds sequentially, cancel outdated PR builds
  group: ci-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

permissions: # Grant write access to github.token within non-pull_request builds
  contents: write
  packages: write

env:
  PLATFORMS: linux/amd64,linux/arm64

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v6
      with:
        fetch-depth: 0
        persist-credentials: false

    - id: release
      name: Prepare release
      uses: mgoltzsche/conventional-release@v1
      with:
        commit-files: chat.html
        # Don't validate git commit messages prior to requiring the convention
        ignore-commits-before: 5b106ddeae56211c542ef1d71415dcf4acded4f2

    - name: Write release version into chat.html
      if: steps.release.outputs.publish
      run: |
        sed -Ei 's/^(\s+const APP_VERSION = ).+$/\1'"'$RELEASE_VERSION';/" chat.html

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v4
      with:
        platforms: ${{ env.PLATFORMS }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v4

    - name: Log into GitHub registry
      if: steps.release.outputs.publish
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build (and push) container image
      uses: docker/build-push-action@v7
      with:
        context: .
        push: ${{ !!steps.release.outputs.publish }}
        platforms: ${{ env.PLATFORMS }}
        tags: |
          ghcr.io/${{ github.actor }}/statelesschatui:latest
          ghcr.io/${{ github.actor }}/statelesschatui:${{ steps.release.outputs.version }}

